[tox]
envlist = local, kubernetes, argo, allok 
isolated_build = True

[testenv]
passenv =
    METAFLOW_HOME
    METAFLOW_PROFILE
    METAFLOW_SERVICE_URL
    METAFLOW_DEFAULT_DATASTORE
    METAFLOW_DATASTORE_SYSROOT_S3
    METAFLOW_KUBERNETES_NAMESPACE
    METAFLOW_KUBERNETES_SECRETS
    METAFLOW_SERVICE_INTERNAL_URL
    AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY
    AWS_ENDPOINT_URL_S3
    AWS_CONFIG_FILE
    HOME
    USER

[testenv:local]
commands = pytest -m local --pyargs metaflow_qa_tests -v {posargs}

[testenv:kubernetes]
deps = kubernetes
commands = pytest -m kubernetes --pyargs metaflow_qa_tests -v {posargs}

[testenv:argo]
deps = kubernetes
commands = pytest -m argo_workflows --pyargs metaflow_qa_tests -v {posargs}

[testenv:all]
ignore_errors = True
commands = 
    {[testenv:local]commands}
    {[testenv:kubernetes]commands}
    {[testenv:argo]commands}
