[tox]
envlist = local, kubernetes, argo
isolated_build = True

[testenv]
passenv =
    METAFLOW_*
    AWS_*
    HOME
    USER

[testenv:local]
commands = pytest -m local --pyargs metaflow_qa_tests -v {posargs}

[testenv:kubernetes]
deps = kubernetes
commands = pytest -m kubernetes --pyargs metaflow_qa_tests -v {posargs}

[testenv:argo]
deps = kubernetes
commands = pytest -m argo_workflows --pyargs metaflow_qa_tests -v {posargs}

[testenv:all]
deps = kubernetes
commands =
    pytest -m local --pyargs metaflow_qa_tests -v {posargs}
    pytest -m kubernetes --pyargs metaflow_qa_tests -v {posargs}
    pytest -m argo_workflows --pyargs metaflow_qa_tests -v {posargs}