[tox]
envlist = local, kubernetes, argo
isolated_build = True

[testenv]
passenv =
    METAFLOW_*
    AWS_*
    HOME
    USER

[testenv:local]
commands = pytest --pyargs metaflow_qa_tests.basic -v {posargs}

[testenv:kubernetes]
deps = kubernetes
commands = pytest --pyargs metaflow_qa_tests.kubernetes -v {posargs}

[testenv:argo]
deps = kubernetes
commands = pytest --pyargs metaflow_qa_tests.argo_workflows -v {posargs}

[testenv:all]
deps = kubernetes
commands =
    pytest --pyargs metaflow_qa_tests.basic -v {posargs}
    pytest --pyargs metaflow_qa_tests.kubernetes -v {posargs}
    pytest --pyargs metaflow_qa_tests.argo_workflows -v {posargs}